spring.application.name=dubbo-provider
server.port=9001

dubbo.scan.base-packages=org.wigo.demo.dubbo.provider
dubbo.application.name=${spring.application.name}

dubbo.registry.address=zookeeper://119.45.186.4:2181

#dubbo.protocols.p1.id=dubbo1
#dubbo.protocols.p1.name=dubbo
#dubbo.protocols.p1.port=20881
#dubbo.protocols.p1.host=0.0.0.0